image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: false

install:
  - java -jar app-ibank.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info "-Dselenide.headless=true"